Repository arkworks-rs/algebra, pull requests merged in 2021-12, with the labels that each got.

#357 Speedup division by vanishing polynomials for dense polynomials
  CHANGELOG.md
  poly-benches/benches/dense_uv_polynomial.rs
  poly/src/polynomial/univariate/dense.rs
Labels: T-performance, D-medium, P-low

#334 Documentation for the ff crate
  ff/README.md
  ff/src/fields/macros.rs
  ff/src/fields/mod.rs
  ff/src/fields/models/cubic_extension.rs
  ff/src/fields/models/fp2.rs
  ff/src/fields/models/quadratic_extension.rs
Labels: T-documentation

#365 Move common fields into `ModelParameters`
  CHANGELOG.md
  ec/src/lib.rs
  ec/src/models/mod.rs
  ec/src/models/short_weierstrass_jacobian.rs
  ec/src/models/twisted_edwards_extended.rs
  test-curves/src/bls12_381/g1.rs
  test-curves/src/bn384_small_two_adicity/g1.rs
  test-curves/src/mnt4_753/g1.rs
  test-templates/src/lib.rs
Labels: D-easy, T-refactor, breaking-change
