Repository arkworks-rs/algebra, pull requests merged in 2022-02, with the labels that each got.

#383 Rename BigInteger::add_nocarry and sub_noborrow and add tests
  CHANGELOG.md
  ff/src/biginteger/mod.rs
  ff/src/biginteger/tests.rs
  ff/src/fields/models/fp/mod.rs
  ff/src/fields/models/fp/montgomery_backend.rs
  ff/src/fields/models/quadratic_extension.rs
Labels: T-test, breaking-change

#306 Upgrade to new `asm` syntax
  CHANGELOG.md
  ff-asm/src/context.rs
  ff-asm/src/context/data_structures.rs
  ff-asm/src/context/mod.rs
  ff-asm/src/lib.rs
  ff-asm/src/unroll.rs
  ff-asm/src/utils.rs
  ff/build.rs
  ff/src/fields/models/fp/montgomery_backend.rs
  ff/src/lib.rs
Labels: T-performance, P-medium, T-refactor

#343 Add Wahby-Boneh hash-to-curve
  CHANGELOG.md
  ec/Cargo.toml
  ec/src/hashing/curve_maps/mod.rs
  ec/src/hashing/curve_maps/swu/mod.rs
  ec/src/hashing/curve_maps/wb/mod.rs
  ec/src/hashing/field_hashers/mod.rs
  ec/src/hashing/map_to_curve_hasher.rs
  ec/src/hashing/mod.rs
  ec/src/hashing/test.sage
  ec/src/hashing/tests.rs
  ec/src/lib.rs
  ff/src/fields/mod.rs
  ff/src/fields/models/cubic_extension.rs
  ff/src/fields/models/fp/mod.rs
  ff/src/fields/models/quadratic_extension.rs
Labels: T-feature, T-performance, T-design

#315 Improve documentation for `ec` traits
  ec/src/glv.rs
  ec/src/lib.rs
  ec/src/models/mod.rs
  ec/src/models/short_weierstrass_jacobian.rs
  ec/src/models/twisted_edwards_extended.rs
  ec/src/wnaf.rs
  ff/src/fields/mod.rs
Labels: T-documentation, P-high
